### ISSUE TITLE
is it working

### ISSUE THREAD

**Issue by MartinNPN** [Limb/TLC5951#3]
Hello,

im testing the part too and found your lib. But i think it didn't work. The first problem i found is that you don't init the SPI System. But evven after fixing this something went wrong. 

Is this code working for you ?

Best Regards,
Martin

**Comment by Limb** [comment]
SPI initialization is left out of the code so as to prevent issues from the use of other SPI libraries. You should be setting up SPI in your code, not the library.

An example is provided below

```
 #define GSLAT 4
 #define XBLNK 5
 #define GSCKGRB 9  

  pinMode(GSCKGRB, OUTPUT);
  analogWrite(GSCKGRB, 127);

  SPI.begin();
  SPI.setClockDivider(SPI_CLOCK_DIV2);

  tlc.init(GSLAT, XBLNK, 0);
  tlc.setLED(0, 0, 0, 4095);
  tlc.setLED(1, 0, 0,  4095);
  tlc.setLED(2, 0, 0, 4095);
  tlc.setLED(3, 0, 0, 4095);
  tlc.setLED(6, 0, 0, 4095);
  tlc.setLED(5, 0, 0, 4095);
  tlc.setLED(4, 0, 0, 4095);
  tlc.setAllDCData(127);
  tlc.setFunctionData(B1111100);
  tlc.setBrightness(95,95,95);
  tlc.update();
```

**Comment by MartinNPN** [comment]
Hello Limb,

i just tested your code but it didn’t work for me. I tested the update every 100 ms and get a flicker but nothing reliable.

Thanks for your help.

I used an arduino pro mini for testing and the following code :

#include "SPI.h"
#include "TLC5951.h"

TLC5951 tlc;

#define GSLAT 9
#define XBLNK 10
#define GSCKGRB 6  

void setup() {

  Serial.begin(9600);

  // Farbclock init
  pinMode(GSCKGRB, OUTPUT);
  analogWrite(GSCKGRB, 127);

  // SPI Init
  SPI.begin();
  SPI.setClockDivider(SPI_CLOCK_DIV2);

  // TLC Init
  tlc.init(GSLAT, XBLNK, 0);
  tlc.setLED(0, 0, 0, 4095);
  tlc.setLED(1, 0, 0, 4095);
  tlc.setLED(2, 0, 0, 4095);
  tlc.setLED(3, 0, 0, 4095);
  tlc.setLED(6, 0, 0, 4095);
  tlc.setLED(5, 0, 0, 4095);
  tlc.setLED(4, 0, 0, 4095);
  tlc.setAllDCData(127);
  tlc.setFunctionData(B1111100);
  tlc.setBrightness(95,95,95);
  tlc.update();

}

Best Regards,
Martin

Am 22.01.2014 um 00:15 schrieb Kenneth Lorthioir notifications@github.com:

**Comment by Limb** [comment]
Try adding this before the pinMode and analogWrite for the GSCKRGB. The TLC5951 requires a rather fast PWM clock that by default is not fast enough, so we have to change the ATMega registers to generate a faster PWM clock.

```
// Set the timer to max speed for fastest PWM generation
int myEraser = 7;             // this is 111 in binary and is used as an eraser
TCCR2B &= ~myEraser;   // this operation (AND plus NOT),  set the three bits in TCCR2B to 0
int myPrescaler = 1;         // this could be a number in [1 , 6]. In this case, 3 corresponds in binary to 011.   
TCCR2B |= myPrescaler;  //this operation (OR), replaces the last three bits in TCCR2B with our new value 011
TCCR0B = TCCR0B & 0b11111000 | 0x01;
```

This should resolve the flicker issue.

**Comment by Limb** [comment]
@MartinNPN I'm not sure if you are still having problems. I was looking over the code and noticed some problems with it. I have uploaded the changes and will be also uploading examples shortly. Please let me know if you have any problems.

**Comment by MartinNPN** [comment]
Hello,

Thanks for your help, i'm really sorry but i didn't test it, because i'm really busy at the moment.
First i must change my hardware, because i had the colour clock on the same timer as the one for the timming, which i want to change.

I will check out your new code and test it at the weekend.

Regards,
Martin

**Comment by aeroyao** [comment]
Hello Limb
i have modify the setBuffer(unit8_t bit) to setBuffer(unit16_t bit)
because in updateGS()
the setBuffer((gsData[a][2] & (1<<c))) <--for bit = 4095 with unit8_t bit will be  000011111111 & 2^c
not be 111111111111 & 2^c
that will that SPI data with gsData[a][2] only have 255 not 4095
but even i fixed that , i still have problem to turn on the LED with right color.

**Comment by Limb** [comment]
@aeroyao Can you post a snippet of the code you changed in the library, as well as your program code in a new issue? I'm going to close this issue out.
